### ISSUE TITLE
MQuake doesn't generate a config by default.

### ISSUE THREAD

**Issue by Rodundo** [BryanHaley/sm64hlmov#1]
On first setup of the mods, MQuake doesn't generate default config, and will default to all 0 values. The issue is resolvable by running the `/mq_server DeleteConfig default` command, but "deleting" a config that doesn't actually exist feels counter-intuitive.

**Comment by BryanHaley** [comment]
Should be resolved as of 3da56698. Feel free to reopen if you have any further issues.
