### ISSUE TITLE
WASD Not working

### ISSUE THREAD

**Issue by ShamoMate** [BryanHaley/sm64hlmov#4]
WASD are not working for me, i can only move by bunnyhopping, is this normal?

**Comment by BryanHaley** [comment]
Sorry, that was a bug. Fixed last night. Update to the latest version. You may need to do "/mq_server DeleteConfig default" as well in the chat (press enter to type)

**Comment by BryanHaley** [comment]
Put in an extra safety check to make double and triple sure the configs are good on first load. Also bolded the "skip intro cutscene" part of the README for extra emphasis.
